name: 'Aliyun FC Action'
description: 'Aliyun Function Compute Action'
author: 'kimmy214'
branding:
  color: 'green'
  icon: 'anchor'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
